import type { Metadata } from 'next';
import { Dancing_Script, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/components/footer';
import { NextIntlClientProvider } from 'next-intl';
import ThemeContextCreator from '@/components/context/ThemeContextCreator';
import DOMPurify from 'isomorphic-dompurify';
import Script from 'next/script';
import { routing } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-dancingScript',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  setRequestLocale(locale);

  console.log('layoddkkkkkkkkkkkkkkkut', locale);
  const cleanThemeSwitcher = DOMPurify.sanitize(`
         
                document.documentElement.classList.toggle(
                  "dark",
                  localStorage.theme === "dark" ||
                    (!("theme" in localStorage) && 
                     window.matchMedia("(prefers-color-scheme: dark)").matches)
                );
 
            `);

  return (
    <html lang={locale}>
      <head>
        <Script
          id="themeSwitcher"
          dangerouslySetInnerHTML={{
            __html: cleanThemeSwitcher,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} dark:bg-black  antialiased mr-5 ml-5 flex flex-col min-h-screen`}
      >
        <NextIntlClientProvider>
          <ThemeContextCreator>
            <Header />

            <main className="grow flex my-3 ">{children}</main>

            <Footer />
          </ThemeContextCreator>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
